# Generated by Django 4.2.5 on 2023-10-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField()),
            ],
        ),
    ]
