# Generated by Django 4.2.5 on 2023-11-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videofile',
            name='video_data',
        ),
    ]
