# Generated by Django 4.2.5 on 2023-10-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mp3File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp3', models.FileField(upload_to='')),
                ('mp3_data', models.BinaryField()),
            ],
        ),
    ]
